apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minion-app-jks
  namespace: {{ .Release.Name }}
data: # To be mounted at /etc/java/jks
  truststore.jks: |
     {{ .Values.truststore.content }}
