apiVersion: v1
kind: Service
metadata:
  labels:
    app: minion
  name: minion
  namespace: {{ .Release.Name }}
spec:
  ports:
    - name: "8201"
      port: 8201
      targetPort: 8201
    - name: "1162"
      port: 1162
      protocol: UDP
      targetPort: 1162
    - name: "1514"
      port: 1514
      protocol: UDP
      targetPort: 1514
  selector:
    app: minion
status:
  loadBalancer: {}
