minion:
 location: pod
 name: myminion
 kafkaBroker:
  address: onms-kafka-bootstrap.shared.svc:9093
  username: ''
  password: ''
 configuration:
  storage:
   dataFolder: 5Gi

core:
 instanceID: monms # Must match OpenNMS Core instance (namespace) 
   
# A common JKS to white-list all CA certificates .
truststore:
 content: '' # A base64 encoded content of the JKS Truststore file.
 password: ''
