name: Sync README file
on:
    push:
     branches:
        - main
     paths:
        - 'README.md'
jobs:
    build:
     permissions:
       contents: write
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: |
           cp -f README.md ${{ runner.temp }}/README.md
       - uses: actions/checkout@v2
         with:
           ref: gh-pages
       - run: |
           cp -f ${{ runner.temp }}/README.md .
           git add README.md
           git commit -m "Sync README from main"
           git push